language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpcs --extensions=php --standard=psr12 -sp src
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover