language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpcs --extensions=php --standard=psr12 -sp src
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
  - travis_retry php php-coveralls.phar --coverage_clover=build/logs/clover.xml